# Generated by Django 3.0.4 on 2020-03-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='note',
            field=models.CharField(default='Not watched', max_length=50, null=True),
        ),
    ]
